### ISSUE TITLE
Windows build warning

### ISSUE THREAD

**Issue by holiman** [karalabe/usb#1]
Random droppings from appveyor windows build:

```
# github.com/ethereum/go-ethereum/vendor/github.com/karalabe/usb
In file included from vendor\github.com\karalabe\usb\libs.go:56:
vendor\github.com\karalabe\usb/hidapi/windows/hid.c: In function 'hid_enumerate':
vendor\github.com\karalabe\usb/hidapi/windows/hid.c:431:5: warning: 'strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
     strncpy(cur_dev->path, str, len+1);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
vendor\github.com\karalabe\usb/hidapi/windows/hid.c:429:11: note: length computed here
     len = strlen(str);
           ^~~~~~~~~~~

```

I'm not sure how to make it happy...

**Comment by holiman** [comment]
This might work:
```
                                len = strlen(str);
                                cur_dev->path = (char*) calloc(len+1, sizeof(char));
-                               strncpy(cur_dev->path, str, len+1);
+                               strncpy(cur_dev->path, str, sizeof(cur_dev->path));
                                cur_dev->path[len] = '\0';
```

**Comment by karalabe** [comment]
Hmm, looked into this. The original code is correct, it's just a misfire of the warning mechanism. By default the last argument of `strncpy` is the size of the destination (as you fixed). In this code however, `len` is actually the size of the source, which is wrong. The thing the compiler is missing is that the destination was created from `len`, so it's length is the same.

**Comment by karalabe** [comment]
Btw, this code is a bit weird altogether. The `strncpy` should fill any leftover space with `\0` anyway, so setting the terminating character is useless anyway. Bleah, won't try to fix C code, I'll mess up something. I'll apply your fix to get rid of the warning and that's that.

**Comment by karalabe** [comment]
Fixed via https://github.com/karalabe/usb/commit/09268c63a892994670a5e7cb8996cd3256954860. Thanks!
