### ISSUE TITLE
Please implement hid_error on macOS and Linux

### ISSUE THREAD

**Issue by benma** [karalabe/usb#22]
https://github.com/karalabe/usb/blob/4ea20957c2104ef4130bb8884e6a6dfb4201a4c8/hidapi/mac/hid.c#L1031-L1036 says TODO. On Windows there is some code there.

It would be nice to see a descriptive error message instead of `unknown failure`.

**Comment by benma** [comment]
Just realized that this should be fixed upstream (https://github.com/signal11/hidapi/issues/123#issuecomment-19460347), sorry for the noise.

**Comment by x1ddos** [comment]
Upstream issue: https://github.com/libusb/hidapi/issues/310
