### ISSUE TITLE
Problem compiling karalabe/usb/hid_enabled

### ISSUE THREAD

**Issue by samu-gataca** [karalabe/usb#9]
github.com/karalabe/usb/hid_enabled.go:22:10:
```
fatal error: './hidapi/hidapi/hidapi.h' file not found
#include "./hidapi/hidapi/hidapi.h"
```

With the last commit, it seems a dependency has been broken.

It occurs trying to deploy a GETH client

**Comment by 2cluster** [comment]
This has to do with the fact that "go mod vendor" only copies go files to the vendor folder. So hidapi.h is not included. This can be fixed by including a empty go module in the file.

**Comment by Rishant-tech** [comment]
hey this error is due to version of github.com/karalabe/usb in your go.mod file
please fix it by replacing  it to "github.com/karalabe/usb v0.0.2"
and execute : 

1 - go clean -modcache
2 - go mod vendor
